### ISSUE TITLE
Unable to login to Google cloud VM

### ISSUE THREAD

**Issue by ephraimm** [garygrossgarten/github-action-ssh#10]
```
Run garygrossgarten/github-action-ssh@release
(node:2787) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
⚠️ The GitHub Action couldn't connect to ***. Error: All configured authentication methods failed
    at doNextAuth (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:9834:17)
    at tryNextAuth (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:9905:5)
    at SSH2Stream.onUSERAUTH_FAILURE (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:10018:5)
    at SSH2Stream.emit (events.js:210:5)
    at parsePacket (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:14914:10)
    at SSH2Stream.module.exports.635.SSH2Stream._transform (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:11933:13)
    at SSH2Stream.Transform._read (_stream_transform.js:189:10)
    at SSH2Stream.module.exports.635.SSH2Stream._read (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:11485:15)
    at SSH2Stream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12) {
  level: 'client-authentication'
}
```
```
⚠️ An error happened executing command ls -a. Error: Not connected
    at Client.module.exports.597.Client.exec (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:10143:11)
    at /home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:20998:20
    at new Promise (<anonymous>)
    at /home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:20997:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:20845:103)
    at _next (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:20847:194)
    at /home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:20847:364
    at new Promise (<anonymous>)
    at /home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:20847:97
 1: 0x9da7c0 node::Abort() [/home/runner/runners/2.263.0/externals/node12/bin/node]
 2: 0xa4e219  [/home/runner/runners/2.263.0/externals/node12/bin/node]
 3: 0xba5d59  [/home/runner/runners/2.263.0/externals/node12/bin/node]
 4: 0xba7b47 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.263.0/externals/node12/bin/node]
 5: 0x13750d9  [/home/runner/runners/2.263.0/externals/node12/bin/node]
Establishing a SSH connection to ***.
##[error]All configured authentication methods failed

```

**Comment by garygrossgarten** [comment]
Closing due to inactivity. This seems to be a problem with the authentication / connection to your ssh server. Please refer to the readme or example workflows for instructions.
