### ISSUE TITLE
Bash Failure

### ISSUE THREAD

**Issue by BillChirico** [garygrossgarten/github-action-ssh#3]
Hello,

I have been using your action for a while, but recently I'm receiving the following error even though the bash script executes successfully.

```
    at SSH.<anonymous> (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:90:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:17:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This used to work fine with no changes to my bash script.

**Comment by avery-pelle** [comment]
I am experiencing a similar thing. I have console warnings that are making the CI run look like a failure. Can we have an option to allow warnings?

**Comment by fatihyildizhan** [comment]
I am gettings this error. Is this related to this issue?

`⚠️ An error happened executing command cd .. && cd folder`

**Comment by garygrossgarten** [comment]
Closing due to inactivity. Feel free to reopen the issue if your issues still exist in the latest version.
