### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by mcmatthevan** [garygrossgarten/github-action-ssh#33]
Hi,
I reinstalled my server today (I upgraded it to 22.04) and when I wanted to reconfigure an automatic "git pull" on it with github actions, I got the following error : 

```
2022-06-17T16:01:54.5793659Z Requested labels: ubuntu-latest
2022-06-17T16:01:54.5793711Z Job defined at: mcmatthevan/mcmatthevan.github.io/.github/workflows/manual.yml@refs/heads/master
2022-06-17T16:01:54.5793848Z Waiting for a runner to pick up this job...
2022-06-17T16:01:55.5591744Z Job is waiting for a hosted runner to come online.
2022-06-17T16:02:00.1063913Z Job is about to start running on the hosted runner: Hosted Agent (hosted)
2022-06-17T16:02:03.4083596Z Current runner version: '2.293.0'
2022-06-17T16:02:03.4116779Z ##[group]Operating System
2022-06-17T16:02:03.4117874Z Ubuntu
2022-06-17T16:02:03.4118907Z 20.04.4
2022-06-17T16:02:03.4119951Z LTS
2022-06-17T16:02:03.4120971Z ##[endgroup]
2022-06-17T16:02:03.4121914Z ##[group]Virtual Environment
2022-06-17T16:02:03.4127424Z Environment: ubuntu-20.04
2022-06-17T16:02:03.4128612Z Version: 20220614.0
2022-06-17T16:02:03.4130088Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220614.0/images/linux/Ubuntu2004-Readme.md
2022-06-17T16:02:03.4131758Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220614.0
2022-06-17T16:02:03.4133020Z ##[endgroup]
2022-06-17T16:02:03.4134065Z ##[group]Virtual Environment Provisioner
2022-06-17T16:02:03.4135125Z 1.0.0.0-main-20220531-1
2022-06-17T16:02:03.4136094Z ##[endgroup]
2022-06-17T16:02:03.4138412Z ##[group]GITHUB_TOKEN Permissions
2022-06-17T16:02:03.4139938Z Actions: write
2022-06-17T16:02:03.4141023Z Checks: write
2022-06-17T16:02:03.4142023Z Contents: write
2022-06-17T16:02:03.4143127Z Deployments: write
2022-06-17T16:02:03.4144072Z Discussions: write
2022-06-17T16:02:03.4144947Z Issues: write
2022-06-17T16:02:03.4145867Z Metadata: read
2022-06-17T16:02:03.4146759Z Packages: write
2022-06-17T16:02:03.4147677Z Pages: write
2022-06-17T16:02:03.4148545Z PullRequests: write
2022-06-17T16:02:03.4149488Z RepositoryProjects: write
2022-06-17T16:02:03.4150483Z SecurityEvents: write
2022-06-17T16:02:03.4151423Z Statuses: write
2022-06-17T16:02:03.4152386Z ##[endgroup]
2022-06-17T16:02:03.4156778Z Secret source: Actions
2022-06-17T16:02:03.4158003Z Prepare workflow directory
2022-06-17T16:02:03.5113185Z Prepare all required actions
2022-06-17T16:02:03.5324836Z Getting action download info
2022-06-17T16:02:03.7919515Z Download action repository 'garygrossgarten/github-action-ssh@release' (SHA:2b10f41b5a33808f6d24eafd253296766308b7c4)
2022-06-17T16:02:04.3231032Z ##[group]Run garygrossgarten/github-action-ssh@release
2022-06-17T16:02:04.3231979Z with:
2022-06-17T16:02:04.3232685Z   command: pull
2022-06-17T16:02:04.3233560Z   host: ***
2022-06-17T16:02:04.3234272Z   username: ubuntu
2022-06-17T16:02:04.3235060Z   passphrase: ***
2022-06-17T16:02:04.3252039Z   privateKey: ***
2022-06-17T16:02:04.3252642Z   port: 22
2022-06-17T16:02:04.3253212Z env:
2022-06-17T16:02:04.3253994Z   CI: true
2022-06-17T16:02:04.3254633Z ##[endgroup]
2022-06-17T16:02:04.6057454Z Establishing a SSH connection to ***.
2022-06-17T16:02:04.6058423Z using provided private key
2022-06-17T16:02:05.1249515Z (node:1464) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2022-06-17T16:02:05.6940921Z ⚠️ The GitHub Action couldn't connect to ***. Error: All configured authentication methods failed
2022-06-17T16:02:05.6944016Z     at doNextAuth (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:11810:17)
2022-06-17T16:02:05.6946487Z     at tryNextAuth (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:11881:5)
2022-06-17T16:02:05.6949026Z     at SSH2Stream.onUSERAUTH_FAILURE (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:11994:5)
2022-06-17T16:02:05.6950603Z     at SSH2Stream.emit (events.js:314:20)
2022-06-17T16:02:05.6951739Z     at parsePacket (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:16890:10)
2022-06-17T16:02:05.6953308Z     at SSH2Stream.module.exports.635.SSH2Stream._transform (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:13909:13)
2022-06-17T16:02:05.6954462Z     at SSH2Stream.Transform._read (_stream_transform.js:191:10)
2022-06-17T16:02:05.6955844Z     at SSH2Stream.module.exports.635.SSH2Stream._read (/home/runner/work/_actions/garygrossgarten/github-action-ssh/release/dist/index.js:13461:15)
2022-06-17T16:02:05.6957059Z     at SSH2Stream.Transform._write (_stream_transform.js:179:12)
2022-06-17T16:02:05.6958304Z     at doWrite (_stream_writable.js:403:12) {
2022-06-17T16:02:05.6959118Z   level: 'client-authentication'
2022-06-17T16:02:05.6960926Z }
2022-06-17T16:02:05.6961779Z ⚠️ An error happened executing command pull. Not connected
2022-06-17T16:02:05.7022204Z ##[error]All configured authentication methods failed
2022-06-17T16:02:05.7033794Z Executing command: pull
2022-06-17T16:02:05.7035802Z ##[error]Not connected
2022-06-17T16:02:05.7051325Z  1: 0xa1a640 node::Abort() [/home/runner/runners/2.293.0/externals/node12/bin/node]
2022-06-17T16:02:05.7052314Z  2: 0xa90649  [/home/runner/runners/2.293.0/externals/node12/bin/node]
2022-06-17T16:02:05.7053970Z  3: 0xc06599  [/home/runner/runners/2.293.0/externals/node12/bin/node]
2022-06-17T16:02:05.7056596Z  4: 0xc08387 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.293.0/externals/node12/bin/node]
2022-06-17T16:02:05.7058069Z  5: 0x140dd19  [/home/runner/runners/2.293.0/externals/node12/bin/node]
2022-06-17T16:02:06.0068014Z Cleaning up orphan processes
```

Here is my workflow file : 
```yaml
name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull palgania server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: pull
          host: ${{ secrets.HOST }}
          username: ubuntu
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
```

The RSA keys which I use work correctly,  I can connect my server through them.
I don't remember any issue the first time I configured it.
I did not try password connection but I can't use it, as it's a password-less login (RSA keys only).

**Comment by EddieEldridge** [comment]
Did you figure it out? I have the exact same problem.

**Comment by mcmatthevan** [comment]
> Did you figure it out? I have the exact same problem.

> Same here, any solution?

I did not find any solution with this action. I just pull manually for now. If you absolutely need something to pull automatically, you should maybe consider using an FTP solution as [FTP-Deploy](https://github.com/marketplace/actions/ftp-deploy).

**Comment by remarkopolo** [comment]
@mcmatthevan thank you for the solution this works for me

**Comment by derBobby** [comment]
@garygrossgarten Is there any chance that you upgrade your action beyond the necessary work-around with the ssh config "PubkeyAcceptedKeyTypes=+ssh-rsa" to be set?

I don't fully understand the issue, GPT says:


> Setting PubkeyAcceptedKeyTypes=+ssh-rsa in your SSH configuration allows the use of the ssh-rsa key algorithm for public key authentication. This has significant security implications:
> 
> Security Impact: Weak Cryptography
> ssh-rsa relies on SHA-1 for signing, which is considered weak due to collision attacks (where different inputs produce the same hash).
> Modern cryptographic research has shown that SHA-1 can be broken with sufficient computational power.
