### ISSUE TITLE
Process complete successfully but package throws error 

### ISSUE THREAD

**Issue by elvis-chuks** [garygrossgarten/github-action-ssh#9]
> events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (D:\a\_actions\garygrossgarten\github-action-ssh\release\dist\index.js:9728:10)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}

**Comment by garygrossgarten** [comment]
@boomalator @elvis-chuks Sorry I don't know how to resolve this. Is this still a problem in the latest release / 0.6.1?

**Comment by elvis-chuks** [comment]
> @boomalator @elvis-chuks Sorry I don't know how to resolve this. Is this still a problem in the latest release / 0.6.1?

I’ll have a look and maybe get back to you, itst been a while

**Comment by garygrossgarten** [comment]
Yeah sorry about that

**Comment by garygrossgarten** [comment]
#21
